### ISSUE TITLE
Black login-dialog-message

### ISSUE THREAD

**Issue by pboguslawski** [nana-4/materia-theme#458] opened 2020-01-07 12:14 UTC
Hi,

In materia-gtk-theme (20190201-1) from debian 10 there is unreadable black text under login box during smart card auth:

![obraz](https://user-images.githubusercontent.com/8192649/71894509-bf01d580-314e-11ea-99c6-acbba6dcc826.png)

Fix that works for us is to change in /usr/share/themes/Materia-compact/gnome-shell/gnome-shell.css...

```
.login-dialog-message-hint {
  padding-top: 0;
  padding-bottom: 20px;
}
```

...to...

```
.login-dialog-message {
  color: rgba(255, 255, 255, 0.4);
  padding-top: 0;
  padding-bottom: 20px;
}
```

Regards,
Paweł

**Comment by nana-4** [comment] 2020-01-16 06:25
Sorry for the late reply, and thanks for reporting the issue.

I think this has already been fixed in master, and is a duplicate of https://github.com/nana-4/materia-theme/issues/436.

For your information, debian's materia-gtk-theme (20190201-1) is a very outdated version :)

Please try the latest master according to https://github.com/nana-4/materia-theme#manual-installation. (Of course don't forget to reinstall the GDM theme.) If it still happens in the latest one, feel free to reopen this.

**Closed by nana-4** 2020-01-16 06:25 UTC
