### ISSUE TITLE
Check boxes are filled with red color

### ISSUE THREAD

**Issue by dhra** [nana-4/materia-theme#182] opened 2017-11-22 16:09 UTC
Hello,
Check boxes are filled with red color, Please check it.

Thanks.

**Comment by nana-4** [comment] 2017-11-22 16:36
I can't reproduce it. Aren't you using customized Materia by yourself?

**Comment by dhra** [comment] 2017-11-23 11:48
1. No.
2. It's ubuntu artful.
3. Here you are: [screenshot](https://picload.org/view/drlprori/0fda7dd3-0237-4333-8de7-ce11f9.png.html)

**Comment by nana-4** [comment] 2017-11-23 16:46
Thanks. Then please let me know the following too:

1. Whether librsvg is installed:
```
sudo apt-get install librsvg2-2 librsvg2-common
```
2. Whether [these `.png` and `.svg` files](https://github.com/nana-4/materia-theme/tree/master/src/gtk-3.0/gtk-common/assets/scalable) exist in your
  `/usr/share/themes/Materia/gtk-common/assets/scalable` directory

I think it is the cause that either one is missing.

**Comment by dhra** [comment] 2017-11-24 07:48
These two library already installed, also scalable directory exits, too. But it needs to root permission:
```sudo nautilus /usr/share/themes/Materia/gtk-common/assets/scalable ```

**Comment by dhra** [comment] 2017-11-24 07:58
I did use launchpad repo, so it I copied whatever about in Materia theme in themes directory into a local theme folder:
```sudo cp /usr/share/themes/Materia* ~/.themes && sudo chmod 777 ~/.themes/Materia* -R```
It's ok now.

**Comment by nana-4** [comment] 2017-11-24 16:33
Aha, permission error? I got it. Anyway it was good to solve this. :)

**Comment by nioncode** [comment] 2018-03-11 19:49
I'm having the same issue on NixOS, so something is probably wrong with nix's packaging there.
The package file looks similar to those of other themes though, and they all work without issues (e.g. adapta, arc, numix).
Do you know if you do things differently than e.g. arc for theming check boxes?

**Comment by nana-4** [comment] 2018-03-12 10:45
@nioncode 

> Are you maybe accessing resources from that location instead of the installed one?

No, I'm not. (i think)

adapta, arc, numix use PNG assets that hard-code colors, but Materia uses **recolorable** SVG assets as Adwaita does. Could you please check if this problem occurs in Adwaita as well?

Also, please, run `ll /nix/store/*-materia-theme-*/usr/share/themes{,/Materia{/gtk-3.22,/gtk-assets/scalable}}` and paste the log.

**Comment by nioncode** [comment] 2018-03-12 11:54
I had to modify your glob to be: /nix/store/\*-materia-theme-\*/ **~~usr/~~** share/themes{,/Materia{/gtk-3.22,/gtk **-common/** assets/scalable}}.
```
$ ll /nix/store/a62vf64girpzr8zgniydqk8rs3s4pyll-materia-theme-20180311/share/themes{,/Materia{/gtk-3.22,/gtk-common/assets/scalable}} 
/nix/store/a62vf64girpzr8zgniydqk8rs3s4pyll-materia-theme-20180311/share/themes:
total 0
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia-compact
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia-dark
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia-dark-compact
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia-light
dr-xr-xr-x 1 root root 176 Jan  1  1970 Materia-light-compact

/nix/store/a62vf64girpzr8zgniydqk8rs3s4pyll-materia-theme-20180311/share/themes/Materia/gtk-3.22:
total 324K
lrwxrwxrwx 1 root root   20 Jan  1  1970 assets -> ../gtk-common/assets
-r--r--r-- 1 root root 157K Jan  1  1970 gtk.css
-r--r--r-- 1 root root 157K Jan  1  1970 gtk-dark.css

/nix/store/a62vf64girpzr8zgniydqk8rs3s4pyll-materia-theme-20180311/share/themes/Materia/gtk-common/assets/scalable:
total 96K
-r--r--r-- 1 root root 237 Jan  1  1970 checkbox-checked-symbolic.svg
-r--r--r-- 1 root root 320 Jan  1  1970 checkbox-checked-symbolic.symbolic.png
-r--r--r-- 1 root root 199 Jan  1  1970 checkbox-mixed-symbolic.svg
-r--r--r-- 1 root root 236 Jan  1  1970 checkbox-mixed-symbolic.symbolic.png
-r--r--r-- 1 root root 196 Jan  1  1970 checkbox-unchecked-symbolic.svg
-r--r--r-- 1 root root 219 Jan  1  1970 checkbox-unchecked-symbolic.symbolic.png
-r--r--r-- 1 root root 287 Jan  1  1970 radio-checked-symbolic.svg
-r--r--r-- 1 root root 532 Jan  1  1970 radio-checked-symbolic.symbolic.png
-r--r--r-- 1 root root 251 Jan  1  1970 radio-mixed-symbolic.svg
-r--r--r-- 1 root root 490 Jan  1  1970 radio-mixed-symbolic.symbolic.png
-r--r--r-- 1 root root 230 Jan  1  1970 radio-unchecked-symbolic.svg
-r--r--r-- 1 root root 485 Jan  1  1970 radio-unchecked-symbolic.symbolic.png
-r--r--r-- 1 root root 244 Jan  1  1970 small-checkbox-checked-symbolic.svg
-r--r--r-- 1 root root 284 Jan  1  1970 small-checkbox-checked-symbolic.symbolic.png
-r--r--r-- 1 root root 200 Jan  1  1970 small-checkbox-mixed-symbolic.svg
-r--r--r-- 1 root root 211 Jan  1  1970 small-checkbox-mixed-symbolic.symbolic.png
-r--r--r-- 1 root root 204 Jan  1  1970 small-checkbox-unchecked-symbolic.svg
-r--r--r-- 1 root root 205 Jan  1  1970 small-checkbox-unchecked-symbolic.symbolic.png
-r--r--r-- 1 root root 301 Jan  1  1970 small-radio-checked-symbolic.svg
-r--r--r-- 1 root root 427 Jan  1  1970 small-radio-checked-symbolic.symbolic.png
-r--r--r-- 1 root root 252 Jan  1  1970 small-radio-mixed-symbolic.svg
-r--r--r-- 1 root root 383 Jan  1  1970 small-radio-mixed-symbolic.symbolic.png
-r--r--r-- 1 root root 236 Jan  1  1970 small-radio-unchecked-symbolic.svg
-r--r--r-- 1 root root 376 Jan  1  1970 small-radio-unchecked-symbolic.symbolic.png
```

Unfortunately, I somehow can't apply Adwaita in my environment at all, do you know another theme I could try to reproduce this with?

**Comment by nana-4** [comment] 2018-03-12 12:20
@nioncode Thanks! I'll check the permissions later.

So could you try my [Adwaita-expt](https://github.com/nana-4/Adwaita-expt)? This uses almost the same technique as Adwaita (and Materia) to render the checkboxes.

**Comment by nana-4** [comment] 2018-03-12 13:12
@nioncode Does the red box appear only in Firefox?
In other words, is it displayed properly in the GTK3 apps (e.g. `gtk3-widget-factory`, Nautilus' "Preferences" window, etc)?

**Comment by nioncode** [comment] 2018-03-12 18:02
Adwaita-expt looks alright in Firefox (just as with no theme at all, which is probably just Adwaita then).
With materia, it seems like the check boxes are only broken in Firefox (maybe others?), but not in Nautilus' "Preferences" window.

**Comment by nana-4** [comment] 2018-03-13 12:25
Hmm, I'm quite confused.

I tried changing the permissions based on your log, but I couldn't reproduce it on Fedora 27.

It's also strange that the check boxes are properly displayed in Nautilus. I guess this is a Firefox specific problem on NixOS. At least it looks like a different problem with this original report.

I'm also confused that why `gtk-common/` directory exists in your `*-materia-theme-20180311/` directory. In `v20180311`, `gtk-common/assets/` should have been replaced by `gtk-assets/`.

Sorry, but I have not found out the cause for now. I'll add `help wanted` tag and investigate it again later.

**Comment by nioncode** [comment] 2018-03-13 20:39
I found out the issue, but don't really understand why it happens.

Broken:
```
echo $XDG_DATA_DIRS
/run/opengl-driver/share:/etc/per-user-pkgs/nion/share:/home/nion/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

Works:
```
echo $XDG_DATA_DIRS
/nix/store/sbk8p8c2dygdxxzlz6fgj1k40xap99aj-materia-theme-20180110/share:/run/opengl-driver/share:/etc/per-user-pkgs/nion/share:/home/nion/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

However, Materia and its variant is symlinked into `/home/nion/.nix-profile/share/themes`, so it should be picked up through the exported `/home/nion/.nix-profile/share`.

**Comment by nioncode** [comment] 2018-03-14 13:02
Seems to be an issue with Firefox, as per my latest findings in https://github.com/NixOS/nixpkgs/issues/36827#issuecomment-372983442.
Probably should be closed here, sorry for the noise.

**Comment by nana-4** [comment] 2018-03-19 16:12
@nioncode Sorry for the delay in my response.
No need to be sorry, thanks for your contribution :)

Closing.

**Closed by nana-4** 2018-03-19 16:12 UTC
Labels: help wanted
