### ISSUE TITLE
Wrong version of gnome-shell.css are contained in Ubuntu PPA

### ISSUE THREAD

**Issue by nomistrebla** [nana-4/materia-theme#225] opened 2018-03-25 17:50 UTC
- Materia version: 20180110-1.2~ubuntu16.04.1
- GTK+ 3 version: 3.18.9-1ubuntu3.3 
- Distribution (and version): Ubuntu 16.04
- Desktop environment (and version): Unity 7.4.5

I'm trying to enable the Materia Loginscreen with Unity [as described in the wiki here](https://github.com/nana-4/materia-theme/wiki/GDM-Theme). For generating the new `gnome-shell-theme.gresource`, the file `gnome-shell-theme.gresource.xml` is required. I can't find this file in any of the Materia theme directories, e.g. `/usr/share/themes/Materia-dark/gnome-shell`. 

Do I require a newer version of the theme? I'm using the @igor-diatlov PPA (ppa:dyatlov-igor/materia-theme) for Ubuntu and can't seem to get a newer version. When using `sudo apt update`, I get the following message:
```
E: The repository 'http://ppa.launchpad.net/dyatlov-igor/materia-theme/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by svnset** [comment] 2018-03-27 17:54
see #228

**Comment by nana-4** [comment] 2018-03-30 08:44
Yes, the wiki is written for a newer version (`v20180311` or later) of the theme, and the PPA was not working, but now it has been fixed.

So I would like to close this now, but please let me know if there is any GDM-theme problem with the new PPA.

Thanks for your report.

**Comment by nomistrebla** [comment] 2018-03-30 11:50
@nana-4 I'm glad to hear the PPA is working now. I just successfully updated to the newest version and again followed the instructions from the wiki, overwriting the `gnome-shell-theme.gresource` file.

Then I switched my display manager from `lightdm` to `gdm3` using
`sudo dpkg-reconfigure gdm3`

Unfortunately, once I restart my system, it crashes right before showing the lock screen. I am then presented with the terminal:

![image](https://user-images.githubusercontent.com/17678744/38136701-92d2f520-3420-11e8-86e4-8a19e0cfd93a.png)

After switching back to `lightdm` and logging in, Ubuntu shows the following crash report:
![image](https://user-images.githubusercontent.com/17678744/38136628-0a05736c-3420-11e8-9015-7f3bce8a8ee5.png)

So as soon as `gnome-shell --mode=gdm` is executed, theres a crash. Maybe the `gnome-shell-theme.gresource` file is corrupt now? Have I forgotten anything? Any help would be greatly appreciated.

**Comment by nana-4** [comment] 2018-03-30 15:11
IIRC, only `sudo dpkg-reconfigure gdm3` is not enough.

Please try:

```
sudo dpkg-reconfigure gdm3
sudo systemctl stop lightdm.service
sudo systemctl start gdm.service
```

**Comment by nana-4** [comment] 2018-03-30 19:12
@igor-dyatlov `materia-gtk-theme - 20180321-1-0ubuntu1~xenial1` deb file (for Ubuntu 16.04.x / GNOME Shell 3.18.x) seems to have a wrong version of `gnome-shell.css`. The deb file for xenial should have `gnome-shell.css` for **3.18**, but in fact it has the CSS for **3.28**. And this GDM crash seems to be due to that.

Could you please fix that in your PPA?

**Comment by nana-4** [comment] 2018-03-30 19:56
@igor-dyatlov 

It seems `materia-gtk-theme - 20180321-1-0ubuntu1~artful1` (for Ubuntu 17.10.x / GNOME Shell 3.26.x) also have `gnome-shell.css` for 3.28, but should have the CSS for **3.26** as well.

Also, just for your information, `materia-gtk-theme` package [for bionic](https://packages.ubuntu.com/bionic/materia-gtk-theme) is now available, so I think `materia-gtk-theme - 20180321-1-0ubuntu1~bionic1` should no longer be needed. I will update the README soon to make it clear.

**Comment by nomistrebla** [comment] 2018-03-31 13:35
@nana-4 Thank you for figuring all this out. For now, I replaced the `gnome-shell.css` with the correct version manually and it works like a charm.

I just switched from Windows to Ubuntu and, as a huge Material Design fan, couldn't be happier now. Thank you so much and keep up the great work! :+1:

**Comment by nana-4** [comment] 2018-03-31 20:35
@igor-dyatlov It seems `bc` is required for `Build-Depends`.

**Comment by igor-dyatlov** [comment] 2018-04-01 00:48
@nana-4 Updated packages

**Comment by nana-4** [comment] 2018-04-01 05:19
@igor-dyatlov Thanks a lot!

I updated the PPA package on Ubuntu 16.04 and confirmed the GDM theme now works fine.

So I'd like to close this issue. :wink:

**Closed by nana-4** 2018-04-01 05:19 UTC
