### ISSUE TITLE
Selected rows in lists completely hides checkboxes in Libre Office

### ISSUE THREAD

**Issue by memeplex** [nana-4/materia-theme#379] opened 2019-05-09 19:07 UTC
Open the options menu and go to the section shown in the screenshot below.

There are similar reports in this tracker but none of them seem to be as extreme as this case.

![image](https://user-images.githubusercontent.com/2845433/57479457-d57c2800-7273-11e9-8c8c-0faddc1f09e4.png)

System: Arch Linux

Package Versions:

* gnome 3.32.1
* materia-gtk-theme 20190315
* libreoffice 6.2.3

**Comment by nana-4** [comment] 2019-05-10 20:22
Thanks for the report. Apparently LibreOffice doesn't load the selection color of GTK theme correctly.

LibreOffice with Materia has a lot of incompatibility issues, so I would like to handle them all in #122 rather than opening issues separately.

Closing as an duplicate of #122.

**Closed by nana-4** 2019-05-10 20:22 UTC
