### ISSUE TITLE
Contrast on Selected item in ListBox and Checked Checkbox is poor

### ISSUE THREAD

**Issue by oct2pus** [nana-4/materia-theme#318] opened 2018-12-01 13:22 UTC
#### Reporter Info

- Materia version: 20180928-1
- GTK+ 3 version: 3.24.1-2
- Distribution (and version): Debian Sid
- Desktop environment (and version): Gnome 3.30
- Related application (and version): Rhythmbox

#### Actual Issue

The contrast between a selected item in a ListBox and a checked checkbox is very poor; one of these items requires a different color to improve.

Here is an image with both the checkmark and a item selected:

![screenshot from 2018-12-01 07-14-32](https://user-images.githubusercontent.com/30452393/49328620-69b1c880-f539-11e8-8252-2602a700a177.png)

**Comment by nana-4** [comment] 2018-12-01 17:45
Thanks for reporting the issue. However, this is a duplicate of #291.

Closing.

**Closed by nana-4** 2018-12-01 17:45 UTC
