### ISSUE TITLE
Firefox with no title bar shows square corners with drop shadow

### ISSUE THREAD

**Issue by torqueyy** [nana-4/materia-theme#306] opened 2018-11-06 09:06 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

I have checked this with the default Adwaita (Light and Dark) themes and variants of Materia, and the issue only seems to affect the default Materia variant.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
**v20180928**
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
**3.24.1**
- Distribution (and version)
**Fedora 29**
- Desktop environment (and version)
**GNOME 3.30.1**
- Related application (and version)
**Firefox 63.0**
- Steps to reproduce
1. Change the system GTK theme to Materia
2. Go to Firefox menu > Customize > Uncheck "Title Bar"
3. The issue becomes visible
- Screenshot(s)
**Adwaita-dark (issue not visible)**
![adwaita-dark](https://user-images.githubusercontent.com/40131158/48053293-34061200-e20f-11e8-9a45-7a3bb76fe5ea.png)

**Materia-dark (issue not visible)**
![materia-dark](https://user-images.githubusercontent.com/40131158/48053351-5f88fc80-e20f-11e8-8788-e22ebd5b2150.png)

**Materia-light (issue not visible)**
![materia-light](https://user-images.githubusercontent.com/40131158/48053382-792a4400-e20f-11e8-9514-e797f55ca4d3.png)

**Materia with Title Bar (issue not visible)**
![materia title bar](https://user-images.githubusercontent.com/40131158/48053427-952de580-e20f-11e8-91d4-40b8e2227d4f.png)

**Materia without Title Bar (issue visible)**
![materia no title bar](https://user-images.githubusercontent.com/40131158/48053463-aaa30f80-e20f-11e8-84f3-b1036d45c8cd.png)

Any help regarding this would be appreciated. Keep up the great work, nana-4!

**Comment by ArchangeGabriel** [comment] 2018-11-06 09:17
Issue is visible on all your screenshot, excepted for the “with Titlebar one” (if you zoom on the -dark cases you will see it, and if you check the colour values in the light case you might see it too). The issue is with Firefox, that initially did not had rounded corners in the CSD case, and now implemented them in strange way. I’m not sure if there is an existing bug report upstream, I don’t have time to look into this currently but that’s where you should be reporting this.

**Comment by torqueyy** [comment] 2018-11-06 09:20
> Issue is visible on all your screenshot, excepted for the “with Titlebar one” (if you zoom on the -dark cases you will see it, and if you check the colour values in the light case you might see it too). The issue is with Firefox, that initially did not had rounded corners in the CSD case, and now implemented them in strange way. I’m not sure if there is an existing bug report upstream, I don’t have time to look into this currently but that’s where you should be reporting this.

Awesome, thank you! I checked Bugzilla but this has not been filed as far as I can see. Feel free to close this issue as it is a Mozilla bug.

**Comment by ArchangeGabriel** [comment] 2018-11-07 16:31
It’s not fixed for me on the latest nightly… Related bugs: https://bugzilla.mozilla.org/show_bug.cgi?id=1408360, https://bugzilla.mozilla.org/show_bug.cgi?id=1489097, https://bugzilla.mozilla.org/show_bug.cgi?id=1493145.

**Comment by m-thorsen** [comment] 2018-11-11 23:05
Firefox 64+ (including current developer edition) includes a fix for rounded corners in most cases (as mentioned in the issues linked), however I did see one odd glitch. 

Using Materia Compact (this does not happen with Adwaita - Unsure if Materia "full size" is affected), the white corners are still visible when the Firefox window overlaps another light window.

Can test and post screenshots tomorrow.

**Comment by nana-4** [comment] 2018-11-12 08:15
@m-thorsen Thanks, screenshots would be helpful.

**Comment by m-thorsen** [comment] 2018-11-12 08:29
Also worth noting that this doesn't seem to affect Materia-dark:

![screenshot from 2018-11-12 09-28-46](https://user-images.githubusercontent.com/14907694/48335253-8014e480-e65d-11e8-8540-c5c66ab5161f.png)

**Comment by nana-4** [comment] 2018-11-12 08:32
@m-thorsen Thanks for your tests & screenshots!

Looks like the cause is that the drop shadow is not rounded.

I'll investigate this.

**Comment by m-thorsen** [comment] 2018-12-07 13:41
FYI: Firefox 64 (with rounded corners in GTK) will be released as stable December 11th    
https://wiki.mozilla.org/Firefox/Roadmap/Updates

**Comment by nana-4** [comment] 2018-12-08 05:48
After some tests, I concluded that this is still an upstream problem. It looks like the upstream devs only tested with Adwaita. Even with HighContrast theme, this problem exists:

![image](https://user-images.githubusercontent.com/9556384/49681980-621c9180-faee-11e8-8980-9e58b37fafea.png)

(HighContrast is one of the official GTK+ theme.)

Since this problem happens even with the upstream official theme, I would like to close this as an upstream issue.

**Closed by nana-4** 2018-12-08 05:48 UTC
Labels: bug
