### ISSUE TITLE
Shutdown botton doesn't works

### ISSUE THREAD

**Issue by SalahAdDin** [nana-4/materia-theme#165] opened 2017-10-18 12:11 UTC
As you can see in the [animation](https://media.giphy.com/media/xT9Igr0ENnouvJQOe4/giphy.gif), when i do click in shut down button doesn't nothing happen.

What's happening?

My system:

- Materia v20171005
- GTK+ 3 3.22.24
- Distribution Antergos ISO-Rolling
- Kernel x86_64 Linux 4.13.5-1-ARCH
- Desktop Gnome 3.26

**Comment by nana-4** [comment] 2017-10-18 17:01
I can't reproduce this.
Is this really a issue of the theme?
Does not occur even with the default Adwaita?

**Comment by SalahAdDin** [comment] 2017-10-20 09:19
@nana-4 You are right, it doesn't works with default theme. It's a problem with gnome.

**Comment by nana-4** [comment] 2017-10-20 09:46
So, as written in the [template](https://github.com/nana-4/materia-theme/blob/master/.github/ISSUE_TEMPLATE.md);

> **Before reporting a bug,** please check whether it also occurs with other themes.

I suppose this is due to the extension(s) you installed.

Anyway I close this issue.

**Closed by nana-4** 2017-10-20 09:46 UTC
Labels: cannot reproduce
