### ISSUE TITLE
Color in Nautilus search bar with Materia-compact application theme

### ISSUE THREAD

**Issue by ckotte** [nana-4/materia-theme#347] opened 2019-01-16 16:40 UTC
**Reporter Info**

- Materia version: git (commit 6386a79)
- GTK3 version: 3.24.3
- Distribution (and version): Arch Linux
- Desktop environment (and version): GNOME 3.30
- Related application (and version): Nautilus 3.30.5

**Actual Issue**

The color of the text and the items in the Nautilus search bar is too dark.

Can you change the color of the search bar text and items in `Materia-compact` to the color in `Materia-dark-compact`? 

**Materia-compact**
![screenshot from 2019-01-16 17-22-11](https://user-images.githubusercontent.com/8488565/51263670-08449c80-19b5-11e9-82d6-28ad7319ea9f.png)

**Materia-light-compact**
![screenshot from 2019-01-16 17-23-15](https://user-images.githubusercontent.com/8488565/51263671-08449c80-19b5-11e9-9976-8851ac1dca00.png)

**Materia-dark-compact**
![screenshot from 2019-01-16 17-23-40](https://user-images.githubusercontent.com/8488565/51263672-08449c80-19b5-11e9-967e-07e082c4c2e9.png)

**Comment by nana-4** [comment] 2019-01-16 21:33
Thanks for your report.

This should be a duplicate of #316.

**Closed by nana-4** 2019-01-16 21:33 UTC
