### ISSUE TITLE
Color problem with some software

### ISSUE THREAD

**Issue by fakhamatia** [nana-4/materia-theme#461] opened 2020-01-19 20:50 UTC
I have a problem with the materia theme and Anydesk and VMware Horizon Client. I send emails many times to Anydesk support but they did not answer at all.
I also ask help from [VMware site](https://communities.vmware.com/message/2907909#2907909) but not answer.
Is there a way to fix this? the problem's for materia theme or software?

- Materia version: 20191017
- GTK3 version: 3.22.30-1ubuntu4
- Distribution: Ubuntu 18.04
- Desktop environment: Gnome 3.28.4
- Related applications: Anydesk 5.5.1 | VMware Horizon Client 5.3.0

![Screenshot from 2020-01-20 00-10-35](https://user-images.githubusercontent.com/20030910/72688205-28ec8880-3b1a-11ea-877f-cfc429f4eaa7.png)

**Comment by nana-4** [comment] 2020-01-21 06:02
Hi,

> the problem's for materia theme or software?

Since it can be reproduced even with the upstream *Adwaita-dark*, I'd say it's not the theme problem.

> Is there a way to fix this?

Those apps seem to use the theme's text colors while hard-coding the background colors, so I think there is no way to fix it on the theme side. It must be fixed on the apps side.

As a temporary workaround, I think you can specify a light theme only for those apps like

```
Exec=env GTK_THEME=Materia <app-name> %U
```

in their `.desktop` files. See https://www.linuxuprising.com/2019/10/how-to-use-different-gtk-3-theme-for.html

**Closed by nana-4** 2020-01-21 06:02 UTC
Labels: question

**Comment by fakhamatia** [comment] 2020-01-21 07:47
@nana-4 
Thanks for help
It work for VMware Horizon Client but Anydesk it looks like use GTK 2.0, right?
```
:~$ ldd /usr/bin/anydesk | grep gtk
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f47d6a65000)
	libgtkglext-x11-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtkglext-x11-1.0.so.0 (0x00007f47d29be000)
```
So I use this in the terminal but Anydesk opens dark again. but if I change theme of the system to light Anydesk its OK.

```
GTK2_RC_FILES=/usr/share/themes/Materia/gtk-2.0/gtkrc /usr/bin/anydesk %u
```

**Comment by nana-4** [comment] 2020-01-21 09:34
I've only tested with the flatpak version of Anydesk, but it seems `GTK_THEME=Materia` works fine to me.
