### ISSUE TITLE
Gnome 3.36 Extensions App Styling

### ISSUE THREAD

**Issue by likeadoc** [nana-4/materia-theme#481] opened 2020-03-25 12:08 UTC
**Reporter Info**

- Materia version: 20200320-1
- GTK3 version: 3.24.14
- Distribution (and version): Manjaro 19
- Desktop environment (and version): Gnome 3.36
- Related application (and version): Gnome Extensions

**Actual Issue**

In the new Gnome Extensions App the "Website" button is cut off and hardly visible.
![Screenshot from 2020-03-25 13-04-59](https://user-images.githubusercontent.com/16107593/77534778-9362d180-6e99-11ea-9ac4-b0cc3179f2a0.png)

**Comment by nana-4** [comment] 2020-03-28 08:53
Thanks for your report.

Basically, such a cutting drop shadow problem is an upstream toolkit bug and can't be fixed by the theme.

However, regardless of that, I'm planning to convert the button style in the "cards" from [contained button style](https://material.io/components/buttons/#contained-button) to [outlined button style](https://material.io/components/buttons/#outlined-button). So once it has landed, _this_ issue will no longer be a problem...

**Comment by nana-4** [comment] 2020-03-28 09:19
I'm going to handle that epic change in https://github.com/nana-4/materia-theme/issues/483, so I'm going to close this one as a duplicate.

**Closed by nana-4** 2020-03-28 09:19 UTC
Labels: upstream issue

**Comment by tuberry** [comment] 2020-04-01 00:28
Another issue of Extensions, the Switch in title bar is too big:
Extensions:
![image](https://user-images.githubusercontent.com/17917040/78086983-25b32a00-73f2-11ea-8963-0111e1611ce7.png)

Gnome-tweaks:
![image](https://user-images.githubusercontent.com/17917040/78087107-83e00d00-73f2-11ea-9be8-98c138fa5f89.png)

**Comment by nana-4** [comment] 2020-04-01 01:45
@tuberry I cannot reproduce it with Materia*-compact.

![image](https://user-images.githubusercontent.com/9556384/78090161-5603c400-7404-11ea-9840-ae1ebad981a1.png)

**Comment by tuberry** [comment] 2020-04-01 02:30
Damn, the font size. It seems that I don't deserve a font size bigger than 13

**Comment by nana-4** [comment] 2020-04-01 11:16
Ah, now I can reproduce it with Roboto, 15 font size. But I wouldn't consider this is a bug in Materia(-compact) because I can reproduce a similar behavior even with the upstream Adwaita :)

(Note that Materia-compact has a much smaller headerbar height than Adwaita, so it's more sensitive to a bigger font size.)

**Comment by tuberry** [comment] 2020-04-01 11:46
Yes, I've noticed the font size  problem in headbar of some applications like [Gedit](https://gitlab.gnome.org/GNOME/gedit/-/issues/250) but the developer say that's remain for subtitle. Again the Extensions needs subtitle, too. :)
