### ISSUE TITLE
GDM pam Yubikey message

### ISSUE THREAD

**Issue by ckotte** [nana-4/materia-theme#436] opened 2019-10-06 19:19 UTC
**Reporter Info**
- Materia version: r1169.8860af49-1
- GTK3 version: 3.24.10
- Distribution (and version): Arch Linux
- Desktop environment (and version): GNOME 3.34.0
- Related application (and version): GDM 3.34.0

**Actual Issue**
The message from PAM is displayed in black. The text should use the same font and color like the other text.

![test](https://user-images.githubusercontent.com/8488565/66274320-ae0aa500-e87d-11e9-9516-71992373add0.jpg)

**Steps to Reproduce (w/ Yubikey)**
1. Configure pam_u2f.so module in `/etc/pam.d/system-auth`
```
auth      required  pam_u2f.so      authfile=/etc/u2f_mappings cue
```
2. Configure `/etc/u2f_mappings` for the user
3. Lock the screen
4. Enter the password
5. The message 'Please touch the device.' is displayed in GDM

**Steps to Reproduce (w/o Yubikey)**
1. Add pam_echo.so module to `/etc/pam.d/system-auth` before all other modules
```
auth      required  pam_echo.so     text
```
2. Lock the screen
3. The message 'text' is displayed in GDM

**Comment by nana-4** [comment] 2019-10-07 13:25
Thanks for your report.

> Configure `/etc/u2f_mappings` for the user

I'm not sure how to configure it. Can you make it clear, please?

**Comment by nana-4** [comment] 2019-10-07 16:21
I tried to fix the problem with the above commit, even though I haven't reproduced the problem yet.

Can you test it? If the problem has been fixed, please ignore my previous comment and close this issue :)

**Comment by ckotte** [comment] 2019-10-07 19:51
Unfortunately, it doesn't work. The text is still black.

The message displayed is the same message that's displayed on the command line if you execute a command with sudo:
```
sudo vi /etc/hosts 
[sudo] password for <user>: 
Please touch the device.
```

> I'm not sure how to configure it. Can you make it clear, please?

You can only reproduce this issue with the procedure described with a Yubikey. 

It looks like you can also display a text with the pam_echo.so module: http://www.linux-pam.org/Linux-PAM-html/sag-pam_echo.html and https://www.redpill-linpro.com/sysadvent/2017/12/11/break-the-glass.html. However, I haven't had time to test this yet.

**Comment by ckotte** [comment] 2019-10-09 18:33
@nana-4 I updated the steps to reproduce this issue. This works without a Yubikey.

**Comment by ckotte** [comment] 2019-10-09 19:33
A reboot suddenly fixed the issue. I guess the gdm process needs to be restarted and a logout isn't sufficient. Thanks.

**Comment by ckotte** [comment] 2019-10-09 19:35
@nana-4 However, it looks a bit odd in this color. Could you please use the same yellow color that's displayed when you enter a wrong password?

**Comment by nana-4** [comment] 2019-10-10 17:43
> I updated the steps to reproduce this issue. This works without a Yubikey.

That worked, thanks!

> However, it looks a bit odd with this color. Could you please use the same yellow color that's displayed when you enter a wrong password?

I agree that it looks a bit odd. But the yellow color means "warning" in this theme, so it may NOT be appropriate semantically. (BTW, the current use of yellow for the wrong password is my failure. Since it's an error rather than a warning, we'll need to use red for it.)

So, I'd like to go with gray color like this:

![image](https://user-images.githubusercontent.com/9556384/66589103-c570c780-ebc8-11e9-8f2e-d412d236ab20.png)

This will be in line with the [Material text fields guidelines](https://material.io/components/text-fields/) :)

**Comment by ckotte** [comment] 2019-10-12 15:23
Ok, makes sense. When will you implement the changes?

**Closed** 2019-10-17 14:31 UTC
Labels: bug

**Comment by ckotte** [comment] 2019-10-18 12:34
Thx. 

> BTW, the current use of yellow for the wrong password is my failure. Since it's an error rather than a warning, we'll need to use red for it.

The color of the error text is still yellow instead of red.

**Comment by nana-4** [comment] 2019-11-08 16:02
> The color of the error text is still yellow instead of red.

It was implemented in ed1a8f910f561c42291e16a38229e245d39fc5d6. (Sorry for the late reply.)

**Comment by ckotte** [comment] 2019-11-09 13:44
It's still yellow on my side. I recompiled the theme: 
```
cd /usr/share/themes/Materia-compact/gnome-shell
glib-compile-resources --target=/usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme.gresource.xml
chmod 0644 /usr/share/gnome-shell/gnome-shell-theme.gresource
```
I also restarted gdm and my system. 

Is there anything missing?

**Comment by nana-4** [comment] 2019-11-11 06:31
Sorry, for some reason I only changed the source SCSS files and didn't regenerate the CSS files. So you need to run `./parse-sass.sh` before running `./install.sh`.

**Comment by ckotte** [comment] 2019-11-13 16:48
I use the AUR package. I don't execute `install.sh`. 

Should the package maintainer add parse-sass.sh to the PKGBUILD just to be sure it will work if you forget to execute it before you commit???
```
package() {
  cd "$srcdir/${pkgname}"
  mkdir -p "${pkgdir}/usr/share/themes"
  ./install.sh -d "${pkgdir}/usr/share/themes"
}
```

**Comment by nana-4** [comment] 2019-11-13 17:50
Okay. Since `master` is a development branch, I tend to skip regenerating CSSs (recently). But I never skip/forget it before making a new release.

So if the AUR package is based on `master`, yes, it would be better. (Note that it requires `sassc` as an additional dependency.)

If the package is based on releases/tags, it would not be necessary.

> Btw. The text is red in the authentication box in the GNOME session, but still yellow in GDM if I type in the wrong password.

If you regenerate CSSs and apply them, red text will appear in GDM :)

**Comment by ckotte** [comment] 2019-11-13 17:56
OK. This works. Thx.

**Comment by nana-4** [comment] 2019-11-13 19:18
There are some mentions about `./parse-sass.sh` in [HACKING.md](https://github.com/nana-4/materia-theme/blob/master/HACKING.md). I thought that's enough for people who want to try the development branch...

> Maybe it makes sense to mention that it needs to be executed if the development branch is used!?

Hmm, not sure. One reason I skip it on `master` is to avoid getting unnecessary bug reports -- someone, especially newcomers, can misunderstand an ongoing implementation as a bug. So I only change the sources when WIP.

However, if you have a good writing idea, MR or suggestion is welcome :)
(Since I'm not good at English, helps to improve documentation are always very welcomed.)
