### ISSUE TITLE
plank rclick menus are wonky

### ISSUE THREAD

**Issue by clumsyfingers** [nana-4/materia-theme#395] opened 2019-06-02 16:56 UTC
everything that has been hovered stays with selected colour https://i.imgur.com/pvIlYPb.png

**Reporter Info**

- Materia version: 
- GTK3 version: 
- Distribution (and version): 
- Desktop environment (and version): 
- Related application (and version): 

**Actual Issue**

**Steps to Reproduce**

1. 
2. 
3. 

**Additional Info**

**Comment by nana-4** [comment] 2019-06-04 04:46
It's duplicate of #300.

But thanks for your report :)

**Closed by nana-4** 2019-06-04 04:46 UTC
