### ISSUE TITLE
new color for materia

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#233] opened 2018-04-05 17:32 UTC
Hi, 
I am trying to get back to the previous colour theme with change_color.sh, but getting this error

```
./change_color.sh -o my-theme-name <(echo -e BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n)
./change_color.sh: line 110: SEL_BG: unbound variable
```

I am fedora 28
Kindly help.

**Comment by actionless** [comment] 2018-04-06 04:03
in example in readme it's quoted

**Comment by n3oxmind** [comment] 2018-05-03 05:03
@rudrab , use this script [colorschemes](https://github.com/n3oxmind/materia-theme/tree/customschemes) very easy to use and not much typing
To install old materia light color scheme
```sh
$ ./materia.sh --scheme materia-oldlight
```
To install old materia dark color scheme
```sh
$ ./materia.sh --scheme materia-olddark
```
To change the titlebar color
```sh
$ ./materia.sh --scheme materia-oldlight --tbg 424242
```
To change accent color of the scheme
```sh
$ ./materia.sh --scheme materia-oldlight --accent c70000
```
and many more options

**Comment by actionless** [comment] 2018-05-03 16:32
using oomox gui is even easier and _actually_ no typing since you don't need to enter the command in the terminal ;)

**Comment by nana-4** [comment] 2018-05-30 02:47
As @actionless  said, you need quotes in that line, @rudrab.

We updated `change_color.sh`, `HACKING.md`, etc. to reproduce the previous Flat-Plat's color scheme more accurately with the script, so I'd like to close this.

**Closed by nana-4** 2018-05-30 02:47 UTC
