### ISSUE TITLE
Broken progress bar in Builder (master)

### ISSUE THREAD

**Issue by t-chaik** [nana-4/materia-theme#348] opened 2019-01-16 21:50 UTC
**Reporter Info**

- Materia version: 6386a791691e15ae0307836d134a05e91dd8ecbf
- GTK3 version: 3.24.2
- Distribution (and version): Fedora 29
- Desktop environment (and version): GNOME 3.30.2
- Related application (and version): Builder master as flatpak

**Actual Issue**

The progress bar, operating in in pulse mode, suffer from visual glitch:

![screenshot from 2019-01-16 21-40-52](https://user-images.githubusercontent.com/8634377/51280863-b4e44580-19d8-11e9-9fad-12e883b31b95.png)

**Steps to Reproduce**

1. Open a project in Builder (gnome-builder).
2. Wait for the code indexing operation to be triggered.

**Comment by nana-4** [comment] 2019-01-18 10:48
Thanks for your report.

This seems to be caused by Builder shipping a _half-broken_ progress bar. I tried to add a workaround somehow, but it didn’t help.

If this is a problem for you, please report it to the upstream Builder. This cannot be fixed by the theme, unfortunately.

**Closed by nana-4** 2019-01-18 10:48 UTC
