### ISSUE TITLE
Xubuntu support, almost runs perfectly other than a couple minor issues and a theme request

### ISSUE THREAD

**Issue by coreybruce** [nana-4/materia-theme#273] opened 2018-08-12 16:37 UTC
Hey just wanted to ask if you can properly support XFCE/Xubuntu 18.04 since it works almost perfectly but can you add a version of the light them were the panel theme is dark please? :+1: :D  

the only issue I can see is the settings when using Materia light is the settings on XFCE uses dark boxes, other than that the theme works fine.

http://i.imgur.com/G1agv2g.png

**Comment by coreybruce** [comment] 2018-08-13 04:12
Also to add some pages on firefox for example Google+ the textbox text is white on white which isn't a XCFE bug

**Comment by aamuu** [comment] 2018-08-15 07:10
+1 for XFCE

**Comment by sergioad** [comment] 2018-08-18 09:12
1

**Comment by sergioad** [comment] 2018-08-18 09:17
Duplicate of #269

**Comment by revast** [comment] 2018-09-17 08:18
I have the problem that this theme, amongst others, changes default icon size of icons in xfce4-panel. 
http://i.imgur.com/uiUJIdN.png

as you can see it is very hard to even see the icons, as the theme renders them so small. thats on stock ubuntu 18.04 with xfce4-panel 4.12.2

**Comment by coreybruce** [comment] 2018-09-18 04:41
> I have the problem that this theme, amongst others, changes default icon size of icons in xfce4-panel.
> http://i.imgur.com/uiUJIdN.png
> 
> as you can see it is very hard to even see the icons, as the theme renders them so small. thats on stock ubuntu 18.04 with xfce4-panel 4.12.2

Hmm that's odd, what icon theme are you using? this is what mine looks like and works without this issue using the same dark theme and flat remix icon theme

http://i.imgur.com/IigZH3q.png

**Comment by revast** [comment] 2018-09-18 14:03
papirus

**Comment by darcn181** [comment] 2018-11-25 19:05
**XFCE is currently moving to GTK3+**, so i don't @nana-4 is going to start doing theming for GTK2+, i started theming the xfce panel since it started using GTK3+ and was able to get good results, **it's now a dark panel in a light theme**
![imagen](https://user-images.githubusercontent.com/28988467/48983258-ea4c7100-f0c2-11e8-8a29-7f281b0b1460.png)
It includes animations, with the animations it doesn't even look like it's actually xfce panel. The overall look of my version is not that much "material", but it looks good so i don't care.

**Comment by mknepper** [comment] 2018-11-29 00:31
I can confirm the bug on Xubuntu 18.04.1 LTS. The theme is perfect except for panel icons. I'm not sure why, but the buttons are cut off, top and bottom. See:

![image](https://user-images.githubusercontent.com/12740958/49191320-baf46900-f33b-11e8-9903-ae7066b6107e.png)

Not totally sure why it's doing this, but other than that, it's a great theme.

**Comment by nana-4** [comment] 2018-11-29 04:13
I'm so sorry for the delay in my response.

I thank you for your reports (that would be helpful), but could you post your issues about Xfce to #60 instead of the new issue?

Materia has not officially supported Xfce yet, so please don't open new issues about Xfce.

Thanks!

**Comment by nana-4** [comment] 2018-11-29 04:14
@coreybruce 

> Also to add some pages on firefox for example Google+ the textbox text is white on white which isn't a XCFE bug

I cannot reproduce it. If you still have the problem, please open a new issue.

**Closed by nana-4** 2018-11-29 04:13 UTC

**Comment by nana-4** [comment] 2018-11-29 04:18
And if you report an issue, please let me know the Xfce **version**, or app **version**. :)

**Comment by revast** [comment] 2018-11-29 09:54
on ubuntu 18.04, default is xfce4-panel 4.12.2 (Xfce 4.12)
