### ISSUE TITLE
Check Box or Radio Button not Visible in Selected Row

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#291] opened 2018-10-08 18:54 UTC
When a row in a table is selected, the checkbox (GtkCheckButton) is not visible.
When a row in a table is selected, the radio button (GtkRadioButton) is not visible.

1. See item 1 in the attached screenshot.
This is an active, selected checkbox when the row has been selected.
2. See item 2 in the attached screenshot.
This is an inactive, selected checkbox when the row has been selected.
3. See item 3 in the attached screenshot.
This is an active, selected radio button when the row has been selected.

I believe the correct solution in all cases should be to "invert" the colors on radio buttons or check boxes when the row is selected. Therefore, when selected in a table row, the check box outline should be in white, and the check mark should be in white as well; the checkbox fill color should be the primary color. Similarly for radio buttons, when selected in a table row, the radio button outline should be in white, and the center "dot" should be in white as well; the radio button fill color should be the primary color.

We also need to account for inactive checked check boxes, or inactive radio buttons. These are typically shown as greyed out. When they are in a row that is selected, the color we probably want to invert the colors, as described above, but add some "gray-ness" or opacity. Item 2 in the first screenshot below shows how an inactive checked check-box currently looks when it appears in a selected table row; as you can see, it is currently indistinguishable from the checked check-box.

(Note, a selected row is different from a highlighted row. A row is highlighted when hovered, but selected when clicked on. The highlight color is a light gray in Materia, but the selected color is Teal, the same color as the widget.)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
585521f

- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
3.22.30

- Distribution (and version)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- Desktop environment (and version)
Gnome-Shell

- Related application (and version)
Glade (sudo apt install glade)
Cubic (https://launchpad.net/cubic)

- Steps to reproduce

Example: Glade
---
Open glade.
Create a new project, and add a new top-lever, such as a GtkWindow.
Select the window widget, anf go to the "Signals" tab.
Click on a signal (such as activate-default) to highlight the row.
Double-click on the Handler column, where it says "<Type here>", and enter a name such as "abc".
Then, click on one of the check boxes in the "Swap: or "After" columns for the new signal.
Notice that the check box is clocked, but it is difficult to distinguish from the background color.
See the 3rd screenshot below for how this looks in Glade.

Example: Cubic
---
Create a new project, and click through until you get to the page with tabs for "Kernels" or "Packages"
Notice the radio buttons and check boxes are hard to see when the row is selected (see the first two screen shots, below).

- Screenshot(s)

![row_with_checkboxes_selected_in_table](https://user-images.githubusercontent.com/19394936/46627522-af897c00-cb08-11e8-90f0-41787c6ca84f.png)

![row_with_radiobutton_selected_in_table](https://user-images.githubusercontent.com/19394936/46627526-b44e3000-cb08-11e8-8454-f9f494a96551.png)

![glade_checked_checkbox_in_selected_row](https://user-images.githubusercontent.com/19394936/46627847-bebcf980-cb09-11e8-8ae9-f37530460abb.png)

**Comment by PJSingh5000** [comment] 2018-10-08 21:12
Here is additional information.

Other themes seem to address this issue to varying degrees of success.

Arc theme does an excellent job.
Would it be possible to mimic the Arc theme solution for the Materia theme?...
- Outline the checkbox in white, and fill the entire inside of the checkbox with white.
- The check mark is colored using the theme's primary or secondary color.
- If a checkbox is inactive, then the outline and fill color are shaded/duller/opaque.

Here is a comparison between Adapta and Arc...

1. Adapta Theme (Active Checked Check-box)
Does a good job of handling active check-boxes.
![glade_with_adapta_theme_and_check_box_in_selected_table_row](https://user-images.githubusercontent.com/19394936/46633323-55de7d00-cb1b-11e8-841b-fbed0f19b4f4.png)

2. Adapta Theme (**Inctive** Checked Check-box)
BUT... Does a bad job of handling inactive check-boxes.
Notice that the inactive checked check-box in the second column is not visible at all.
![cubic_with_adapta_theme_and_check_box_in_selected_table_row](https://user-images.githubusercontent.com/19394936/46633348-668ef300-cb1b-11e8-90f9-ebe18af62c83.png)

3. Arc-Darker Theme (Active Checked Check-box)
Does a good job of handling active check-boxes.
![glade_with_arc_darker_theme_and_check_box_in_selected_table_row](https://user-images.githubusercontent.com/19394936/46633848-f2554f00-cb1c-11e8-9ad9-32f4b570cfa1.png)

4. Arc-Darker Theme (**Inctive** Checked Check-box)
ALSO... Does a good job of handling inactive check-boxes.
Notice that BOTH the active/checked and the inactive/checked check-boxes are visible when the row is selected.
![cubic_with_arc_darker_theme_and_check_box_in_selected_table_row](https://user-images.githubusercontent.com/19394936/46633608-32680200-cb1c-11e8-93a1-07f3e06a26d7.png)

**Comment by darcn181** [comment] 2018-10-10 02:16
I was able to fix the issue by changing the line 2725 to color: white;
![imagen](https://user-images.githubusercontent.com/28988467/46709260-d6cb7080-cc10-11e8-8c1f-1e27b0e40c3c.png)
Do i make a PR then?

**Comment by nana-4** [comment] 2018-10-10 11:44
Good point. I was planning to fix this, but I postponed it because I was busy.

Thanks for your report, anyway.

**Comment by nana-4** [comment] 2018-10-10 11:44
@darcn181 With SCSS, we also need to fix the checked `switch` as well.

![image](https://user-images.githubusercontent.com/9556384/46733765-2f137880-cccc-11e8-89c0-23c4df41662c.png)

Maybe it would be better to fix it by myself to make sure. But thank you for your help.

**Comment by PJSingh5000** [comment] 2018-10-12 01:13
I appreciate you looking into this.

There are four different scenarios that need to be tested for check-boxes.
1. Active, checked check-box with hover selection
2. Active, unchecked check-box with hover selection
3. Inactive, checked check-box with hover selection
4. Inactive, unchecked check-box with hover selection

These same four scenarios need to be tested for radio-buttons, as well.

Since `gtk3-widget-factory` doesn't show all four scenarios, here is a little test program written in Python. The program allows you to hover over each row in order to see what the check-boxes look like.

(To keep the program as short, it only shows check-boxes, not radio-buttons, and you can't actually check or un-check the check-boxes).

1. Copy and save both files as `test_291.py` and `test_291.ui`, respectively, in the same directory. 
2. Open a terminal and navigate to the directory where you saved the files.
3. Install Python if you don't have it (`sudo apt install python3.6`).
4. Make sure `test_291.py` is executable (`chmod +x ./test_291.py`).
5. Then launch by typing `./test_291.py`.

---
![screenshot from 2018-10-11 20-57-16](https://user-images.githubusercontent.com/19394936/46841863-5b94c680-cd98-11e8-8c23-76a27d79f0c9.png)

---
### `test_291.py`
```
#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class MainWindowHandlers(Gtk.Window):
    def on_destroy(self, *args):
        Gtk.main_quit()

builder = Gtk.Builder()
builder.add_from_file("test_291.ui")
handlers = MainWindowHandlers()
builder.connect_signals(handlers)
window = builder.get_object('window')
list_store = builder.get_object('list_store')
list_store.append([True, True, 'Test active, checked check-box with hover selection.'])
list_store.append([True, False, 'Test active, unchecked check-box with hover selection.'])
list_store.append([False, True, 'Test inactive, checked check-box with hover selection.'])
list_store.append([False, False, 'Test inactive, unchecked check-box with hover selection.'])
window.show()
Gtk.main()
```

---
### `test_291.ui`
```
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkListStore" id="list_store">
    <columns>
      <!-- column-name None - Decide if the checkbox is active (not displayed)-->
      <column type="gboolean"/>
      <!-- column-name Yes/No? - Show checkbx as checked or unchecked -->
      <column type="gboolean"/>
      <!-- column-name Description - Discription of checkbox state -->
      <column type="gchararray"/>
    </columns>
  </object>
  <object class="GtkWindow" id="window">
    <property name="can_focus">False</property>
    <property name="border_width">18</property>
    <signal name="destroy" handler="on_destroy" swapped="no"/>
    <child>
      <placeholder/>
    </child>
    <child>
      <object class="GtkTreeView" id="tree_view">
        <property name="visible">True</property>
        <property name="can_focus">True</property>
        <property name="model">list_store</property>
        <property name="hover_selection">True</property>
        <child internal-child="selection">
          <object class="GtkTreeSelection" id="tree_selection"/>
        </child>
        <child>
          <object class="GtkTreeViewColumn" id="tree_view_column_1">
            <property name="sizing">autosize</property>
            <property name="min_width">10</property>
            <property name="title" translatable="yes">Yes/No?</property>
            <property name="clickable">True</property>
            <child>
              <object class="GtkCellRendererToggle" id="cell_renderer_1"/>
              <attributes>
                <attribute name="activatable">0</attribute>
                <attribute name="active">1</attribute>
              </attributes>
            </child>
          </object>
        </child>
        <child>
          <object class="GtkTreeViewColumn" id="tree_view_column_2">
            <property name="title" translatable="yes">Description</property>
            <property name="clickable">True</property>
            <child>
              <object class="GtkCellRendererText" id="cell_renderer_2"/>
              <attributes>
                <attribute name="text">2</attribute>
              </attributes>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by darcn181** [comment] 2018-10-12 02:56
The active one shows correctly with my change
![imagen](https://user-images.githubusercontent.com/28988467/46845253-a585a880-cda8-11e8-9131-d9330a8e5de9.png)
Except the inactive one
![imagen](https://user-images.githubusercontent.com/28988467/46845263-b6ceb500-cda8-11e8-9697-c5c56072cb5f.png)
I'll have a look into it, if you could make another test program but with switches it would help more imo.

**Comment by PJSingh5000** [comment] 2018-10-12 03:06
Take a look at what [Arc theme does in this situation](https://user-images.githubusercontent.com/19394936/46633608-32680200-cb1c-11e8-93a1-07f3e06a26d7.png).

I think they use white (as you did in the 1st row), but its opacity is increased, so it looks grayish when the row is highlighted.

I'll create another test program and post it.

**Comment by darcn181** [comment] 2018-10-12 03:08
@PJSingh5000 Updated comment with solution, check it out!

**Comment by PJSingh5000** [comment] 2018-10-12 03:15
Looks good!

I meant to suggest to also test your solution with a LIGHT theme.
(I presume the highlighted rows would look similar?).
Would you post a screen shot with a light theme?

**Comment by darcn181** [comment] 2018-10-12 03:17
The rows should look the same as they always have the highlight color as background (The green), so everything should look the same in the light variant as in the dark one.

**Comment by PJSingh5000** [comment] 2018-10-13 03:10
Here is the test program with radio-buttons and check-boxes.
I presume you meant "radio-buttons" instead of "switches".
The [GtkCellRendererToggle widget only supports check-boxes and radio-buttons](https://developer.gnome.org/gtk3/stable/GtkCellRendererToggle.html#gtk-cell-renderer-toggle-set-radio).

The instructions are the same as before:

1. Copy and save both files as `test_291.py` and `test_291.ui`, respectively, in the same directory. 
2. Open a terminal and navigate to the directory where you saved the files.
3. Install Python if you don't have it (`sudo apt install python3.6`).
4. Make sure `test_291.py` is executable (`chmod +x ./test_291.py`).
5. Then launch by typing `./test_291.py`.

---
![screenshot from 2018-10-12 23-09-38](https://user-images.githubusercontent.com/19394936/46900668-ee566380-ce73-11e8-8488-65c716c3070b.png)

---
### `test_291.py`
```
#!/usr/bin/python3
# https://github.com/nana-4/materia-theme/issues/291

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class MainWindowHandlers(Gtk.Window):
    def on_destroy(self, *args):
        Gtk.main_quit()

builder = Gtk.Builder()
builder.add_from_file("test_291.ui")
handlers = MainWindowHandlers()
builder.connect_signals(handlers)
window = builder.get_object('window')
list_store = builder.get_object('list_store')
list_store.append([True, True, 'Test active, checked radio-button or check-box with hover selection.'])
list_store.append([True, False, 'Test active, unchecked radio-button or check-box with hover selection.'])
list_store.append([False, True, 'Test inactive, checked radio-button or check-box with hover selection.'])
list_store.append([False, False, 'Test inactive, unchecked radio-button or check-box with hover selection.'])
window.show()
Gtk.main()
```

---
### `test_291.ui`
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://github.com/nana-4/materia-theme/issues/291 -->

<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkListStore" id="list_store">
    <columns>
      <!-- column-name None - Decide if the radio-button or check-box is active (not displayed)-->
      <column type="gboolean"/>
      <!-- column-name Yes/No? - Show radio-button or check-box as checked or unchecked -->
      <column type="gboolean"/>
      <!-- column-name Description - Description of checkbox state -->
      <column type="gchararray"/>
    </columns>
  </object>
  <object class="GtkWindow" id="window">
    <property name="can_focus">False</property>
    <property name="border_width">18</property>
    <signal name="destroy" handler="on_destroy" swapped="no"/>
    <child>
      <placeholder/>
    </child>
    <child>
      <object class="GtkTreeView" id="tree_view">
        <property name="visible">True</property>
        <property name="can_focus">True</property>
        <property name="model">list_store</property>
        <property name="hover_selection">True</property>
        <child internal-child="selection">
          <object class="GtkTreeSelection" id="tree_selection"/>
        </child>
        <child>
          <object class="GtkTreeViewColumn" id="tree_view_column_1">
            <property name="sizing">autosize</property>
            <property name="min_width">10</property>
            <property name="title" translatable="yes">Radio Button</property>
            <property name="clickable">True</property>
            <child>
              <object class="GtkCellRendererToggle" id="cell_renderer_1">
                <property name="radio">True</property>
              </object>
              <attributes>
                <attribute name="activatable">0</attribute>
                <attribute name="active">1</attribute>
              </attributes>
            </child>
          </object>
        </child>
        <child>
          <object class="GtkTreeViewColumn" id="tree_view_column_2">
            <property name="sizing">autosize</property>
            <property name="min_width">10</property>
            <property name="title" translatable="yes">Check Box</property>
            <property name="clickable">True</property>
            <child>
              <object class="GtkCellRendererToggle" id="cell_renderer_2"/>
              <attributes>
                <attribute name="activatable">0</attribute>
                <attribute name="active">1</attribute>
              </attributes>
            </child>
          </object>
        </child>
        <child>
          <object class="GtkTreeViewColumn" id="tree_view_column_3">
            <property name="title" translatable="yes">Description</property>
            <property name="clickable">True</property>
            <child>
              <object class="GtkCellRendererText" id="cell_renderer_3"/>
              <attributes>
                <attribute name="text">2</attribute>
              </attributes>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by darcn181** [comment] 2018-10-13 20:48
I actually meant about the switches, @nana-4 said that the switches need a fix too, but i'll try to fix it without  a program. Nonetheless i'm going to try your program and see if the radio buttons are broken or something.

**Comment by PJSingh5000** [comment] 2018-10-14 06:36
Good progress! I'll see if I can come up with something to test the switches.

**Comment by darcn181** [comment] 2018-10-28 18:47
Hey @nana-4 what program did you use that showed the switch in a row?
@PJSingh5000 Rows appear too on .sidebars, maybe there?
the only thing i've come up with to fix the switches is these lines
```
.view:selected switch:checked slider {
  background-color: white;
  color: white;
}
```
~~~~~~~~~~~~~~~~~ or ~~~~~~~~~~~~~~~~~
```
row:selected switch:checked slider {
  background-color: white;
  color: white;
}
```

**Comment by nana-4** [comment] 2018-11-11 20:31
I'm sorry for the late reply.

> Hey @nana-4 what program did you use that showed the switch in a row?

I used `gnome-control-center`.

And for future reference, I recommend you to use the [GTK+ Inspector](https://blog.gtk.org/2017/04/05/the-gtk-inspector/) to find out where a specific widget is contained. (sorry if you already knew this.)

![image](https://user-images.githubusercontent.com/9556384/48317275-cc96fa80-e632-11e8-9ec1-0cfa198f9a31.png)

However, I am considering another solution for this (while making the theme closer to the current Material Design guidelines). So please wait until the solution is committed.

Anyway thanks a lot for your help @PJSingh5000 @darcn181 :)

**Comment by darcn181** [comment] 2018-11-12 12:29
Don't worry, i'm here to help, the lines in my last comment (the ones that say row) would fix the issue though, but i want to see the new design you have in mind.

**Comment by nana-4** [comment] 2018-12-03 06:57
> i want to see the new design you have in mind.

@darcn181 Sorry I'm late. Here you are:

![image](https://user-images.githubusercontent.com/9556384/49348841-29924780-f6eb-11e8-9e9f-7a4de54970c8.png)

This is based on the refreshed Material Design guidelines: https://material.io/design/interaction/states.html#selected

**Comment by darcn181** [comment] 2018-12-03 23:50
Looks good to me, seems better than before tbh

**Comment by nana-4** [comment] 2018-12-04 07:52
Yes. Basically all selected items will have the transparency as per Material Design guidelines.

**Comment by darcn181** [comment] 2018-12-04 17:30
Ok. this is what i understand, Every selected item will have a color like blue which will be used in text or in the image, this CurrentColor will be applied to the background using 0.26 transparency, and images and text will have the same color.

**Comment by darcn181** [comment] 2018-12-05 21:44
Don't worry, it will look just fine, here's my version, i have a border on the left though
![imagen](https://user-images.githubusercontent.com/28988467/49545896-56925600-f8b5-11e8-94f4-8a5c17df68b2.png)

**Comment by nana-4** [comment] 2018-12-06 17:42
I've fixed this. Now you can try it from latest master branch :)
(Though it still may need some refining...)

Closing.

**Closed by nana-4** 2018-12-06 17:42 UTC
Labels: bug

**Comment by darcn181** [comment] 2018-12-06 21:39
Wow, new materia looks awesome, nice job @nana-4, looks weird sometimes though
![imagen](https://user-images.githubusercontent.com/28988467/49612747-0cc07300-f97c-11e8-8b5a-9a51c335ac1e.png)
And you should fix the xfce panel, you can use .xfce4-panel or #XfcePanelWindow, buttons just need it's backgroud-color changed to transparent, like this
![imagen](https://user-images.githubusercontent.com/28988467/49613372-d2f06c00-f97d-11e8-86e4-8813696375c7.png)

**Comment by PJSingh5000** [comment] 2018-12-07 03:06
Thank You! I really appreciate the thoughtful work you have put into this particular bug and into this theme (which in my humble opinion is the best out there!).

Some observations:

- The rounded corners on the selected item in the Nautilus sidebar is beautiful. (It would be nice to see this treatment in all lists; I don't know if that is possible?).

- I think there may be some unintended side-effects. For example, I selected text in this web page. The selected ext was highlighted in light blue. When I switched to another application, leaving the text highlighted, the highlight color turned black. Is this normal/expected?

- The lower contrast between the text and the lighter highlighted background is a little hard on my eyes. For example, the blue-on-blue in Nautilus below, is hard to distinguish from two feet away; I did notice that it is not as bad in the example at material.io, because of the dark purple text they used. I think I need to use this new design little more to get used to it. :)

Here is a picture of the rounded highlighted corners of selected items in Nautilus. Very nice!...
![screenshot from 2018-12-06 21-17-21](https://user-images.githubusercontent.com/19394936/49623643-7f414b00-f99c-11e8-8640-59853ac25c8c.png)

**Comment by nana-4** [comment] 2018-12-08 05:12
Thanks guys for your kind comments and feedback :)

> And you should fix the xfce panel, you can use .xfce4-panel or #XfcePanelWindow, buttons just need it's backgroud-color changed to transparent, like this

It is intentional. Only with the underline I thought it's hard to distinguish which task button is checked (at a glance), so I added the background-color.

> (It would be nice to see this treatment in all lists; I don't know if that is possible?)

Code-wise, it's difficult or impossible, sadly :(

> I think there may be some unintended side-effects. For example, I selected text in this web page. The selected ext was highlighted in light blue. When I switched to another application, leaving the text highlighted, the highlight color turned black. Is this normal/expected?

Yeah, it's unintended behavior. We need some workarounds for web browsers...

> The lower contrast between the text and the lighter highlighted background is a little hard on my eyes. For example, the blue-on-blue in Nautilus below, is hard to distinguish from two feet away; I did notice that it is not as bad in the example at material.io, because of the dark purple text they used. I think I need to use this new design little more to get used to it. :)

Yeah, I understand. I'm still not sure whether this is a matter of  getting used to it or color scheme issue. We'd need an observation period or some more feedback...

**Comment by darcn181** [comment] 2018-12-09 00:08
@nana-4 what i meant is that,  **the text color is white in the unchecked buttons**
![imagen](https://user-images.githubusercontent.com/28988467/49691892-c8230c00-fb22-11e8-9a58-869bfa2f511a.png)
The underline looks just fine on my end, i said that you should make the buttons transparent because of the white text and because this makes all elements on the panel transparent, so people can change the color of the panel and it will change the buttons too, supposing that you make the text of the panel black (which you should make it like that on the light variant of the theme) this is how it would look
![imagen](https://user-images.githubusercontent.com/28988467/49691945-040aa100-fb24-11e8-8cb6-1eb253fcc3c4.png)
So then people can change the panel color to white and it will look good, like this
![imagen](https://user-images.githubusercontent.com/28988467/49691961-5ea3fd00-fb24-11e8-80a6-5e8d5bc402ef.png)
Or green for whatever reason.
![imagen](https://user-images.githubusercontent.com/28988467/49691969-a6c31f80-fb24-11e8-94a4-5e1a3a948b28.png)
I would take out the shadows of the buttons too imo, and as it has a bottom border like all .flat things it would follow more the Material Design Guidelines

**Comment by GrowtopiaJaw** [comment] 2021-04-26 09:52
> Thank You! I really appreciate the thoughtful work you have put into this particular bug and into this theme (which in my humble opinion is the best out there!).
> 
> Some observations:
> 
>     * The rounded corners on the selected item in the Nautilus sidebar is beautiful. (It would be nice to see this treatment in all lists; I don't know if that is possible?).
> 
>     * I think there may be some unintended side-effects. For example, I selected text in this web page. The selected ext was highlighted in light blue. When I switched to another application, leaving the text highlighted, the highlight color turned black. Is this normal/expected?
> 
>     * The lower contrast between the text and the lighter highlighted background is a little hard on my eyes. For example, the blue-on-blue in Nautilus below, is hard to distinguish from two feet away; I did notice that it is not as bad in the example at material.io, because of the dark purple text they used. I think I need to use this new design little more to get used to it. :)
> 
> 
> Here is a picture of the rounded highlighted corners of selected items in Nautilus. Very nice!...
> ![screenshot from 2018-12-06 21-17-21](https://user-images.githubusercontent.com/19394936/49623643-7f414b00-f99c-11e8-8640-59853ac25c8c.png)

May I ask which icon theme are you using? I'm really interested and would like to try it out!

**Comment by PJSingh5000** [comment] 2021-04-26 15:51
It is called Papirus:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
