### ISSUE TITLE
Is Materia dead?

### ISSUE THREAD

**Issue by NotteShock** [nana-4/materia-theme#611] opened 2022-01-28 00:53 UTC
I'm just worried about this theme.... this theme is great and it's my favorite theme since adapta is discontinued. But i think i need to worry about this theme may dead soon because there's no activity for 2 months and there's lot of issue that haven't resolved, I'm just worry about the fate of this theme, sorry if it makes the creator distracted

**Comment by thkrz** [comment] 2022-01-31 12:32
Looks like it, not sure. However, this is a duplicate of #599

**Closed** 2022-01-31 15:13 UTC
Labels: question
