### ISSUE TITLE
IME boxes and shell popups have extraneous white background box

### ISSUE THREAD

**Issue by wuyangyu2010** [nana-4/materia-theme#433] opened 2019-09-22 23:12 UTC
**Reporter Info**

- Materia version: materia-gtk-theme-20190912-1.fc30.
- GTK3 version: 3.24.11
- Distribution (and version): Fedora 30
- Desktop environment (and version): Gnome3 3.32.2
- Related application (and version): 

**Actual Issue**

In Fedora 30, early versions of Materia had no such problems, but after updating the materia version, IME boxes and shell popups had white background borders, and different types of problems were found in testing other GTK themes.
![Screenshot from 2019-09-23 07-15-47](https://user-images.githubusercontent.com/22276427/65395784-0cda1400-ddd2-11e9-9448-eeb28f0326b5.png)
![Screenshot from 2019-09-23 07-15-53](https://user-images.githubusercontent.com/22276427/65395785-0d72aa80-ddd2-11e9-8704-f499da40a6de.png)

**Steps to Reproduce**

1. 
2. 
3. 

**Additional Info**

**Comment by cthbleachbit** [comment] 2019-09-23 15:51
Please update the issue title to reflect the actual issue and please use English so that others may understand... Probably something like "IME boxes and shell popups have extraneous white background box".

**Comment by Ghostium** [comment] 2019-09-24 08:53
Try regenerating the shell theme.
 https://github.com/nana-4/materia-theme/tree/master/src/gnome-shell#installation 
That removed the white borders for me. 

However, this introduced weird formatting issues when searching. Only 1-2 search results are shown and the "submenu" options are cut off with a dot. 

![Screenshot from 2019-09-24 10-44-20](https://user-images.githubusercontent.com/15706162/65496341-92d08a80-deb8-11e9-9a3c-bdb230bd1143.png)

My versions:
Materia version: 9940151df24ecd92c8f1de3e511dbf6cf176d681
GTK3 version: gtk3-3.24.11-1.fc30.x86_64.rpm
Distribution (and version): Fedora 30
Desktop environment (and version): gnome-shell-3.32.2-2.fc30.x86_64.rpm
Related application (and version):

**Comment by nana-4** [comment] 2019-09-25 12:08
Yeah, it seems @Ghostium is right.

@wuyangyu2010 I think your problem should be fixed by reinstalling Materia GDM theme. Please try it.

**Comment by nana-4** [comment] 2019-09-25 12:09
@cthbleachbit Thanks, I've updated the issue title as you suggested :)

**Comment by nana-4** [comment] 2019-09-25 12:18
> However, this introduced weird formatting issues when searching. Only 1-2 search results are shown and the "submenu" options are cut off with a dot.

@Ghostium Strange, I couldn't reproduce it on both Xorg and Wayland.

Did you manually customize anything? From your screenshot, it looks like you have applied the gnome-shell **3.34** theme to gnome-shell **3.32**.x.

**Comment by Ghostium** [comment] 2019-09-25 17:40
Thanks, I accidentally used 3.34 styles for 3.32. 

I always thought that the install.sh script copies every version and gnome just picks the right folder, as I never really dived into how themes work. I build materia-theme in a Docker container so the gnome-shell package is not installed and the version can't be derived defaulting to $LATEST_GS_VERSION.

I did not find a CLI flag or environment variable to set the gnome version, so I just run sed in my .spec file:
```bash
sed -i 's/\${GS_VERSIONS\[-1\]}/3.32/g' install.sh
```
Maybe $GS_VERSION should only be set if it not already defined (so it can be passed as an environment variable). if test -z "$GS_VERSION"; then if command -v etc..

**Comment by wuyangyu2010** [comment] 2019-09-26 00:35
@nana-4 Thank you. The problem has been solved.

**Comment by wuyangyu2010** [comment] 2019-09-26 01:09
@nana4 I removed Fedora's RPM installation package and cloned material theme from GitHub. After the new installation, all problems were solved.
![Screenshot from 2019-09-26 09-09-11](https://user-images.githubusercontent.com/22276427/65650429-62662900-e03d-11e9-971c-36a5af2ca62f.png)
![Screenshot from 2019-09-26 09-09-14](https://user-images.githubusercontent.com/22276427/65650430-62662900-e03d-11e9-8300-30f61deeff2c.png)
![Uploading Screenshot from 2019-09-26 09-09-30.png…]()

**Comment by nana-4** [comment] 2019-09-26 09:20
@wuyangyu2010 I think you didn't need to remove the RPM package and clone the repo; just regenerating the GDM theme should have been fine. But anyway I'm glad to hear that :)

**Comment by nana-4** [comment] 2019-09-26 09:21
@Ghostium 

> I always thought that the install.sh script copies every version and gnome just picks the right folder,

Regarding GTK themes, that's true. But gnome-shell uses [St toolkit](https://developer.gnome.org/st/) instead of GTK, and it doesn't support versioned theme folders. So we need to pick a proper version of gnome-shell theme in the script.

> I build materia-theme in a Docker container so the gnome-shell package is not installed and the version can't be derived defaulting to $LATEST_GS_VERSION.

Sorry I'm not familiar with Docker, so I may be wrong something but: Does that mean you have installed gnome-shell in the OS directly, not in the Docker container? If so, why don't you build materia-theme in both OS (for gnome-shell & gdm) and the Docker container (for GTK apps)? 

> so I just run sed in my .spec file

Can you show me all the code/description in your .spec file? Then I can understand more background :)

**Comment by nana-4** [comment] 2019-09-26 09:43
@Ghostium Probably it would be better to talk about it in another issue. Please, use #434 to reply :)

**Closed by nana-4** 2019-09-26 09:43 UTC
Labels: invalid
