### ISSUE TITLE
xfce4 appmenu and plank issues

### ISSUE THREAD

**Issue by numberokta** [nana-4/materia-theme#268] opened 2018-07-21 12:47 UTC
When i use "materia" theme, "appmenu" use a lot of cpu (about 15-20%) and when i right click on icons in "plank", background color stuck on hovering.
everything else works great.

- Materia v20180519
- GTK+ v3.22.30-2
- Ubuntu v18.04
- Xfce v4.12 + metacity v1:3.28.0-1
- xfce4-appmenu-plugin v0.6.94  (Source: vala-panel-appmenu)

![untitled](https://user-images.githubusercontent.com/20727200/43035672-79d423ae-8d09-11e8-9e0c-e6eb4b476014.png)
![untitled1](https://user-images.githubusercontent.com/20727200/43035673-7a1d6c8a-8d09-11e8-9bdd-61a7253129a1.png)

**Comment by nana-4** [comment] 2018-11-29 04:33
I'm so sorry for the delay in my response.

Currently, Materia is not officially supporting Xfce (see #60), but

> When i use "materia" theme, "appmenu" use a lot of cpu (about 15-20%)

maybe it's a duplicate of #177. In any case I'll recheck it when I'll try to support Xfce.

> when i right click on icons in "plank", background color stuck on hovering.

Plank is also not officially supported yet (see #206), but I think it's a duplicate of #300.

So I'll close this as "duplicate". Thanks for the report anyway!

**Closed by nana-4** 2018-11-29 04:33 UTC
