### ISSUE TITLE
Gnome 3.36 Known Wifi Networks Text Overlap

### ISSUE THREAD

**Issue by malcolmseyd** [nana-4/materia-theme#482] opened 2020-03-28 06:50 UTC
**Reporter Info**
* Materia git (built March 25th, 2020)
* Gnome 3.36
* GTK 3.24.14
* Manjaro
* Application: `gnome-control-center wifi`

**Actual Issue**
Text overlaps in the "Known Wifi Networks" dialog's settings menu. This window is non-resizable.

![Screenshot from 2020-03-27 23-42-29](https://user-images.githubusercontent.com/56709101/77817046-26139400-7085-11ea-8fe0-8bdd05fe3c5b.png)

**Comment by nana-4** [comment] 2020-03-28 08:01
I can't reproduce it.

What happens with Adwaita?

**Comment by malcolmseyd** [comment] 2020-03-28 22:37
This issue seems to appear on Adwaita as well.
![Screenshot from 2020-03-28 15-34-03](https://user-images.githubusercontent.com/56709101/77835453-efcc2800-7109-11ea-8334-9a7e476866a0.png)

**Comment by nana-4** [comment] 2020-03-28 23:51
So this is not the theme issue.

Please, check our [issue template](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=&template=bug_report.md&title=) again: 

> IMPORTANT NOTE:
> 
> Before reporting a bug, please check whether it also happens with other themes, especially Adwaita or Adwaita-dark. If it happens even with the upstream default theme, it is very likely an upstream issue.

Closing.

**Closed by nana-4** 2020-03-28 23:51 UTC
