### ISSUE TITLE
Some SVG assets become black with librsvg 2.41.2

### ISSUE THREAD

**Issue by sbsbs15** [nana-4/materia-theme#195] opened 2018-01-06 15:26 UTC
Hi @nana-4 , recently I updated the theme (package materia-theme-git from AUR) and noticed that assets used to display indicators in gnome-shell dash (I'm using Dash to dock too) are now black.

![captura de pantalla de 2018-01-06 15-31-24](https://user-images.githubusercontent.com/15521217/34641035-f2f48266-f2fd-11e7-8ef9-021e7a9cf8d3.png)

Using gtk 3.22.26.

Thanks for your work!!

**Comment by nana-4** [comment] 2018-01-07 18:15
Hi, thank you for your report!

For the moment, I cannot reproduce it and I have no idea why they become black...

Could you tell me the version of Dash to dock you are using?

**Comment by sbsbs15** [comment] 2018-01-07 20:23
Yes! I'm using Dash to dock v61, but I updated to version 62 now and the issue persist.
I noticed that viewing the assets folder from nautilus indicators are displayed black too.

![captura de pantalla de 2018-01-07 21-10-52](https://user-images.githubusercontent.com/15521217/34653748-be76a1ba-f3f0-11e7-969a-ebbaa72e0404.png)

I don't know what happens because my laptop updated with the same packages don't have this issue...

**Comment by bil-elmoussaoui** [comment] 2018-01-07 20:34
maybe a librsvg issue, try to downgrade it?

**Comment by sbsbs15** [comment] 2018-01-07 20:47
Exactly! Problem with librsvg 2.41.2, downgrading to 2.41.0 all work fine.
Thanks @bil-elmoussaoui!

**Comment by bil-elmoussaoui** [comment] 2018-01-07 20:49
not all heros wear capes :laughing:

**Comment by AlexWayfer** [comment] 2018-01-08 05:08
> Exactly! Problem with librsvg 2.41.2, downgrading to 2.41.0 all work fine.

Is it a bug of `librsvg` and you can give a link to it, or some SGVs in this repo should be fixed for the new version of `librsvg` and the current issue should be opened?

**Comment by nana-4** [comment] 2018-01-08 09:27
@bil-elmoussaoui Thank you for answering instead of me!

@AlexWayfer Exactly.

I have not confirmed yet, but I think this is a bug of the upstream `librsvg` (because those SVGs won't become black in web browsers, etc). And we may need a workaround until upstream fixes this bug...

Anyway I would like to reopen this until the issue is properly handled.

**Comment by AlexWayfer** [comment] 2018-01-08 09:42
[Changelog](https://github.com/GNOME/librsvg/blob/master/NEWS) between patch-versions isn't small. So, what about version 2.41.1?

**Comment by actionless** [comment] 2018-01-08 11:31
i've fixed it like that: https://github.com/actionless/oomox-archdroid-icon-theme/commit/86ff3f5efab95a3b3f755163a6e36be4e9aa25cf

**Comment by nana-4** [comment] 2018-01-08 12:10
@actionless Thanks!

I guess the `fill` attribute no longer inherits to child elements (only when it's in the `<svg>` element?) on the new version of `librsvg`.

I’d report it to the upstream later.

**Comment by nana-4** [comment] 2018-01-09 11:31
Now I reported this issue to the upstream: https://gitlab.gnome.org/GNOME/librsvg/issues/181

**Comment by nana-4** [comment] 2018-01-10 16:33
I've added a workaround for gnome-shell & metacity. So now it should work well in those environments with librsvg 2.41.2.

However this problem still remains in Unity, so I'd like to rename and keep opening this issue.

**Comment by actionless** [comment] 2018-01-11 14:28
in 2.42.0 it seems still unfixed

**Comment by nana-4** [comment] 2018-01-13 01:34
Good news. Upstream fixed the bug and will appear in 2.42.1. So I'd like to close this issue.

**Closed by nana-4** 2018-01-13 01:34 UTC
Labels: bug, upstream issue
