### ISSUE TITLE
Hard To See Dock in Gnome

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [nana-4/materia-theme#408] opened 2019-07-14 10:24 UTC
When using a light background the dock becomes really hard to see. 
A possible fix is to either make the dock darker or make it opaque like in Adwaita.

![Screenshot from 2019-07-14 11-22-53](https://user-images.githubusercontent.com/7698035/61182379-fcffc000-a629-11e9-9819-c1cd7b84c690.png)

**Comment by nana-4** [comment] 2019-07-14 17:23
Looks like the dark overlay (vignette effect) in the overview is disabled in your GNOME Shell. Are you applying any extension or customization to remove the dark overlay?

If I'm wrong, can you provide your wallpaper (in order to test the accessibility issue by myself)?

**Comment by KUPOinyourWINDOW** [comment] 2019-07-14 19:24
Nope, AFAIK the dark overlay is a feature of 3.34 which isn't out yet?
![Anime Bird](https://user-images.githubusercontent.com/7698035/61188317-4b867c00-a675-11e9-8511-99e739d46f16.jpg)

There's the weeb wallpaper, hope it helps

**Comment by nana-4** [comment] 2019-07-15 19:33
> AFAIK the dark overlay is a feature of 3.34 which isn't out yet?

No, AFAIK the dark overlay is a feature since 3.0 :) In 3.34, it will be just darker (according to the current master branch of gnome-shell).

> There's the weeb wallpaper, hope it helps

Thanks for the wallpaper. Here is a reproduction on my environment; gnome-shell 3.32.2, no extensions (except for "User themes"):

![image](https://user-images.githubusercontent.com/9556384/61243262-86c2a100-a782-11e9-84ba-81f2cfbd37c4.png)

In comparison with my screenshot, your overview looks a bit lighter. (Plus, your top bar has a strange effect.) I don't know the exact cause, but at least it's NOT due to the theme. (Maybe your driver bug? idk...)

So I think this issue can be closed as a bug outside this theme. Agree?

**Comment by KUPOinyourWINDOW** [comment] 2019-07-16 02:33
With your help I've figured out the cause; an extension for gnome called "blyr". I assumed because I had it set to only affect the bar at the top, and not the activities overview that it wouldn't affect anything. It gets rid of the vignette effect though. Totally not an issue with the theme, my bad, sorry.

**Comment by nana-4** [comment] 2019-07-16 13:38
OK, then closing.

**Closed by nana-4** 2019-07-16 13:38 UTC
