### ISSUE TITLE
Cut icons

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/materia-theme#92] opened 2016-12-10 16:04 UTC
I'm using this theme (v3.22.20161109) on arch linux xfce (4.12). Gtk 3 version is 3.22.5.
The icons in the alt-tab menu, and the icon of the application menu in the panel are cut. Note that the icon in the panel is cut even by increasing the size of the same. This does not happen with other themes.
![screenshot_2016-12-10_16-51-20](https://cloud.githubusercontent.com/assets/7833001/21074493/af8e5700-befa-11e6-8d42-6ef653be84dd.png)
(icon of the application menu is in the upper left corner)
![screenshot_2016-12-10_16-48-44](https://cloud.githubusercontent.com/assets/7833001/21074492/af8865f2-befa-11e6-9e9b-8b94e02e7be7.png)
![screenshot_2016-12-10_16-48-22](https://cloud.githubusercontent.com/assets/7833001/21074494/af94d486-befa-11e6-83a6-f8eb368c0248.png)

**Comment by nana-4** [comment] 2017-10-29 09:48
I think this is also a particular issue of Xfce, so I'd like to close this as a duplicate of #60.

**Closed by nana-4** 2017-10-29 09:48 UTC
Labels: bug
