### ISSUE TITLE
Unintended highlighting without user input

### ISSUE THREAD

**Issue by torqueyy** [nana-4/materia-theme#409] opened 2019-07-15 10:37 UTC
**Reporter Info**

- Materia version: https://github.com/nana-4/materia-theme/commit/7f84b1aacb20c37f25269263e32b63aeb71bab89
- GTK3 version: 3.24.10
- Distribution (and version): Fedora 30
- Desktop environment (and version): GNOME 3.32.2
- Related application (and version): `nautilus` 3.32.1-stable

**Actual Issue**

Please close this issue if the behaviour is unintended!

The current version of Materia highlights the left Nautilus menu item by default when the menu button is clicked (open new window) - before the cursor passes over it. This behaviour is not repeated in Adwaita nor Materia v20190315.

**Materia current**

![new1](https://user-images.githubusercontent.com/40131158/61210112-9aa0df80-a74f-11e9-82b2-84d669b87cc8.png)

**Materia v20190315**

![old1](https://user-images.githubusercontent.com/40131158/61196945-15550500-a726-11e9-9eb6-ca45d97070e3.png)

**Adwaita current**

![adwaita1](https://user-images.githubusercontent.com/40131158/61210405-801b3600-a750-11e9-9a02-e27d4cfb28a6.png)

**Steps to Reproduce**

1. Open the menu from the header bar of `nautilus`

**Comment by nana-4** [comment] 2019-07-15 19:40
Thanks for the report.

Yeah, it is an intended behavior :) That highlight indicates the [focus state](https://material.io/design/interaction/states.html#focus). (So if you press the <kbd>Enter</kbd> key, that highlighted button will be pressed.)

Not showing the focus ring in Adwaita and Materia v20190315 is, I think, a bug or unwanted behavior of GTK3 (due to the strange behavior of CSS `outline`). That behavior would probably be fixed in GTK4, though.

So I'm going to close this.

**Closed by nana-4** 2019-07-15 19:40 UTC

**Comment by torqueyy** [comment] 2019-07-17 05:07
Is it a bug that the highlight does not change when the cursor hovers over another button? My apologies for not including this in earlier screenshots.

![Screenshot from 2019-07-17 17-04-53](https://user-images.githubusercontent.com/40131158/61348588-562f5400-a8b5-11e9-8bcb-a0fb51a220f7.png)

**Comment by nana-4** [comment] 2019-07-18 10:35
No, it's not a bug. The top right button is still in focus, unless you click another button or press <kbd>Tab</kbd>.

I understand that it may look a bit strange at first glance, but this is in line with Material Design guidelines. See https://material.io/design/interaction/states.html#focus for details.

You can also see this behavior in the [online demo](https://material-components.github.io/material-components-web-catalog/#/component/button) by Google.
