### ISSUE TITLE
flicker on all gtk 3 apps under kde.

### ISSUE THREAD

**Issue by ripefig** [nana-4/materia-theme#321] opened 2018-12-05 20:32 UTC
#### Reporter Info

- GTK: 3.24.1-1ubuntu2
- Materia: 20180928-1 
- Distribution (and version): Kubuntu 18.10
- Desktop environment (and version): KDE Plasma Version: 5.14.4
- Related application (and version): Every app that uses theme.

#### Actual Issue
Flicker observed on all hovered elements:

![deepin-screen-recorder_select area_20181205232004](https://user-images.githubusercontent.com/45201036/49542201-f962c880-f8e5-11e8-89eb-ae0638444c0a.gif)

![deepin-screen-recorder_select area_20181205233326](https://user-images.githubusercontent.com/45201036/49542295-3dee6400-f8e6-11e8-87bf-91af701d594f.gif)

**Comment by ripefig** [comment] 2018-12-05 20:34
Recommendation: disable animations until they are fixed upstream.

**Comment by nana-4** [comment] 2018-12-06 06:17
I cannot reproduce this **at all** with **any** DEs (including KDE Plasma 5.14.3 that tested on VM).

Does this problem _really_ happen only with Materia?
What about other themes?

**Comment by nana-4** [comment] 2018-12-06 06:17
> Recommendation: disable animations until they are fixed upstream.

No. LibreOffice buttons and treeview rows are always non-animatable. So I don't think it makes sense.
But you can locally disable GTK+ animations. Try this:

```
gsettings set org.gnome.desktop.interface enable-animations false
```

**Comment by ripefig** [comment] 2018-12-06 10:56
It happens with all the themes that highlight on hover. Adwaita doesn't have this effect so it works fine. Now that I recall, I've actually observed this on Gnome as well just under a year ago (but I switched to Adwaita and then forgot that this bug ever existed).

**Comment by ripefig** [comment] 2018-12-06 11:13
`gsettings set org.gnome.desktop.interface enable-animations false`

That fixes the issue on all true GTK3 programs. LibreOffice still flickers.

**Comment by nana-4** [comment] 2018-12-06 14:05
> It happens with all the themes that highlight something on hover. Now that I recall, I've actually observed this on Gnome as well just under a year ago.

So, did you see this annotation when opening the ticket?

> Before reporting a bug, please check whether it also occurs with the upstream default theme.
If the bug also occurs with the upstream default theme, it is very likely an upstream issue.

If it happens with all the themes, it's definitely not the theme issue. (Maybe it's likely your your graphics driver issue, I guess.) Such a problem should be reported to the upstream (maybe Kubuntu?)...

Closing.

**Closed by nana-4** 2018-12-06 14:05 UTC

**Comment by ripefig** [comment] 2018-12-06 22:53
My bad. Yeah, it's a GTK issue. Definitely not a problem with graphics drivers though, since I have Intel. 

The bug has existed since the inception of GTK+ 3, I don't think they are ever going to fix it. Animations cause problems in GTK.

**Comment by ripefig** [comment] 2018-12-06 23:17
nvm, it's resolved on my Fedora VM. Apparently it's caused by Ubuntu not showing tool-tips or something.
