### ISSUE TITLE
oomox fails to generate gtk-dark.css with proper accent color

### ISSUE THREAD

**Issue by lelgenio** [nana-4/materia-theme#412] opened 2019-07-24 02:42 UTC
Editing the accent color does not seam affect gtk-dark.css

steps to reproduce:
- make a theme with different accent color
- open a gtk program which uses gtk-dark.css(totem, eog)
most notably the progress-bar on totem is always the default color

also, this can be fixed by generating materia dark with the same accent color and replacing gtk-dark.css:
```bash
mv oomox-materia-dark/gtk-3.0/gtk.css oomox-materia/gtk-3.0/gtk-dark.css
```

**Comment by nana-4** [comment] 2019-07-29 03:18
This looks like a duplicate of #353. So I'm going to close this one as a duplicate.

Thanks for your report anyway.

**Closed by nana-4** 2019-07-29 03:18 UTC
Labels: oomox
