### ISSUE TITLE
Latest Ubuntu Materia packages broken

### ISSUE THREAD

**Issue by hackel** [nana-4/materia-theme#223] opened 2018-03-22 23:21 UTC
Reaching out to @igor-dyatlov because he's got issues disabled on his repo.

You probably know this already, but the last two builds on your PPA produced empty packages:
```
materia-theme:
  Installed: 20180311-1.4.1~ubuntu17.10.1
  Candidate: 20180311-1.4.1~ubuntu17.10.1
  Version table:
 *** 20180311-1.4.1~ubuntu17.10.1 100
        100 http://ppa.launchpad.net/dyatlov-igor/materia-theme/ubuntu artful/main amd64 Packages
        100 http://ppa.launchpad.net/dyatlov-igor/materia-theme/ubuntu artful/main i386 Packages
        100 /var/lib/dpkg/status

$ dpkg -L materia-theme
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/materia-theme
/usr/share/doc/materia-theme/changelog.Debian.gz
/usr/share/doc/materia-theme/copyright
```
I previously had 20180110-1.2~ubuntu17.10.1 installed and it was working fine, but I can no longer find this particular version on the PPA for some reason.

I installed this version and it seems to be working fine on my Ubuntu 17.10 install:
http://ppa.launchpad.net/dyatlov-igor/materia-theme/ubuntu/pool/main/m/materia-theme/materia-theme_20180110-1.2~ubuntu16.04.1_all.deb

Since that package is for Gnome 3.18, I wasn't sure if there would be any incompatibilities, but so far I haven't noticed any issues.  Thanks for keeping these packages updated!

**Comment by nana-4** [comment] 2018-03-24 06:47
@hackel Thanks for reporting this!

I will assign this issue to @igor-dyatlov. Thanks in advance. :smiley:

**Comment by igor-dyatlov** [comment] 2018-03-24 17:16
@nana-4 After switching to the new package build script for ppa, a problem arose. As it turned out with the installation of the script **install.sh**
At this point, I've disabled the repository until the problem is fixed.

My suggestion is to write an install script for make. How it is implemented in the [adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme)

**Closed** 2018-03-30 07:31 UTC

**Comment by nana-4** [comment] 2018-03-30 08:03
@igor-dyatlov Sorry for the late reply.

I'm not familiar with make, but when I learn it more I'd switch the installation script to make (or meson?).

Thanks for your advice.

**Comment by igor-dyatlov** [comment] 2018-03-30 18:29
@nana-4 my spare time, I'll try to do something. Most recommend meson.

**Comment by nana-4** [comment] 2018-03-30 19:36
@igor-dyatlov Sounds great! Thanks. :)
